-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 04, 2025 at 04:44 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipe`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `title`, `image`, `ingredients`, `instructions`, `user_id`, `created_at`, `updated_at`) VALUES
(1, 'Baked chicken with cider and smoky bacon', 'uploads/chicken-with-cider1.webp', '1 tablespoon olive oil\r\n4 chicken Maryland pieces, skin on\r\n4 rashers smoky bacon, chopped\r\n1 medium sized brown onion, peeled, halved and sliced\r\n1 clove garlic, finely chopped\r\n4-5 sprigs of thyme, plus more for serving\r\n2 heaped teaspoons Dijon mustard\r\n450 ml dry apple cider\r\nsea salt and black pepper', 'Preheat oven to 180 C. \r\nPlace a large frying pan over a medium heat and add the olive oil.\r\nAdd the chicken and brown the pieces all over until golden brown. \r\nRemove from the pan, and set aside. Place the onion, garlic, bacon and thyme into the pan and saute until the onion is softened.\r\nTake care not to burn the garlic. Turn the heat up to high. Pour in the cider and cook for a couple of minutes before adding and Dijon mustard.\r\nUse a wooden spoon to stir and scrape off any of the delicious crispy bits stuck to the bottom of the pan.\r\nRemove from the heat. Place the sauce in the bottom of a medium-sized casserole dish. Add the chicken pieces in a single layer and spoon over some of the sauce. Season well with salt and freshly ground black pepper. \r\nCover tightly with foil and bake in the oven for 35-40 minutes. Remove the foil and spoon a little more of the sauce over the chicken and return to the oven for another 10 minutes. \r\nRemove the cooked thyme before serving and scatter over about a tablespoon more of fresh thyme leaves, and another generous grind of black pepper.', 2, '2024-12-26 14:22:31', '2024-12-27 11:21:43'),
(2, 'Satay', 'uploads/dish-3.jpg', ' \"500g chicken thighs, diced\",\r\n                    \"1/2 cup peanut butter\",\r\n                    \"2 tbsp soy sauce\",\r\n                    \"1 tbsp honey\",\r\n                    \"1 tbsp lime juice\",\r\n                    \"Skewers for grilling\"', '\"Mix all marinade ingredients and coat the chicken. Let it sit for 1 hour. Skewer the chicken and grill until cooked through.\"', 2, '2024-12-26 14:28:13', '2024-12-27 11:24:19'),
(3, 'Pavlova', 'uploads/dish-1.jpg', '\"4 egg whites\",\r\n                    \"1 cup sugar\",\r\n                    \"1 tsp cornflour\",\r\n                    \"1 tsp white vinegar\",\r\n                    \"Whipped cream and fruits for topping\"', '\"Whip egg whites until stiff, gradually adding sugar. Fold in cornflour and vinegar. Bake at 120°C for 1 hour. Cool and top with whipped cream and fruits.\"', 2, '2024-12-26 14:28:46', '2024-12-27 11:24:19'),
(4, 'ChickenGrill', 'uploads/dish-4.jpg', '\"4 skinless, boneless chicken breast halves\",\r\n                    \"¼ cup lemon juice, plus wedges for serving\",\r\n                    \"¼ cup olive oil\",\r\n                    \"2 teaspoons dried oregano or parsley\",\r\n                    \"1 teaspoon seasoning salt\",\r\n                    \"½ teaspoon ground black pepper\",\r\n                    \"½ teaspoon onion powder\"', '\"Gather the ingredients. Preheat an outdoor grill for medium-high heat, and lightly oil the grate. Marinate chicken for 30 minutes to 12 hours. Grill until cooked.\"', 2, '2024-12-26 14:29:19', '2024-12-27 11:24:19'),
(5, 'Cake Batik', 'uploads/KekBatik.jpg', '1 small can/397 ml/14 oz Condensed Milk*\r\n1 ¾ cups Chocolate Milk Powder**\r\n⅔ cup Butter\r\n4 Eggs\r\n1 Tablespoon Vanilla Extract\r\n250 - 300 grams Petit Beurre / Marie Biscuits\r\nFor Garnish Sliced Almonds (optional)', 'Crush biscuits into quarters (optional). Set aside.\r\nPrepare a cake pan (round, loaf, square – up to you) by lining it with foil or parchment paper and grease well with cooking spray or butter. I used a 35cm x 9cm loaf pan for this.\r\nIn a medium large pot or wok, gently melt butter on medium heat.\r\nMix in condensed milk and chocolate malt powder. Stir till combined.\r\nAdd in eggs and stir continuously on medium to medium high till it thickens to the consistency of hot fudge. Or till it reaches the soft ball stage on a candy thermometer. 118°C to 120°C (235°F to 240°F).\r\nOnce it has thickened, add in vanilla extract. Stir to mix.\r\nStir in biscuits is using it crushed. Pour into cane pan and flatten the top.\r\nIf you choose not to crush the biscuits : Spread a layer of fudge into cake pan and layer it with biscuits. Repeat till you run out of fudge.\r\nGarnish with sliced almonds (optional).\r\nLeave cake to cool for an hour then cover and refrigerate overnight.', 2, '2024-12-27 07:53:04', '2024-12-27 11:24:19'),
(6, 'Cookies', 'uploads/cookies.jpg', '130 g All-purpose Flour\r\n40 g Caster Sugar\r\n100 g Unsalted Butter\r\n60 g Dark Choco Chip', '1. Measure and prepare the 4 ingredients needed.\r\n2. By using spoon to mix well the unsalted butter, caster sugar and all-purpose flour.\r\n3. Next, add the chocolate chip and mix well.\r\n4. Measure same size of the dough. By using 140-150’ bake for 23 minutes, until light golden brown colour.', 2, '2024-12-27 07:56:44', '2024-12-27 11:24:19'),
(7, 'Rainbow salad with haloumi', 'uploads/rainbow-salad2.webp', '120 g mixed salad leaves\r\n1 each of medium-sized red, yellow and green capsicums\r\n2 carrots\r\n1 medium-sized fresh beetroot\r\n250 g mixed cherry tomatoes\r\n2 cobs fresh corn\r\nhandful fresh flat-leaf parsley\r\n1 small bunch chives\r\n1/3 cup pepitas\r\n1/2 cup pecan nuts\r\n180 -200 g block of haloumi\r\n3 tablespoons extra virgin olive oil\r\njuice of 1 large lemon\r\n2 teaspoons capers\r\n1/2 teaspoon chilli flakes\r\nsea salt and black pepper', 'Heat oven to 180 C. Place the pepitas and pecans on a baking tray and bake for 10 minutes until they smell toasty and are satisfyingly crunchy. Take out of the oven and set aside to cool. Dice capsicums into 1 cm square pieces. Peel carrots and julienne. Peel beetroot and julienne. Keep the beetroot separate from the other ingredients so its rich purple juice doesn’t stain the other ingredients. Cut the tomatoes into halves. Using a sharp knife cut the kernels off the corn cobs. Roughly chop the parsley and snip the chives. Make the dressing. Place 2 1/2 tablespoons olive oil, the lemon juice, capers and chilli flakes in a small glass jar with a lid. Shake well and then season to taste with sea salt and black pepper. When ready to serve, toss all the salad ingredients together and place in a serving dish. Heat a non-stick pan over medium heat and add the remaining olive oil. Cut the haloumi into 8 pieces and pan fry until golden. Place the haloumi on the salad, pour over the dressing and serve immediately.', 2, '2024-12-27 08:19:53', '2024-12-27 11:24:19'),
(8, 'Potatoes with rosemary and sea salt', 'uploads/potatoes-with-rosemary5.webp', '8 medium sized red-skinned potatoes\r\n1 tablespoon good olive oil\r\nsea salt and freshly ground black pepper\r\n4 sprigs of fresh rosemary', 'Preheat oven to 180 C.\r\nUsing a mandolin slice the potatoes very thinly. Place in a medium sized glass bowl and cover with cold water. Let sit for about 20 minutes then drain and dry well with a tea towel.\r\n\r\nPick the leaves off the rosemary and place in the base of a 20 cm round or 18 cm square dish. This enables their earthy flavour to infuse the potatoes as they cook and keeps them from burning and becoming bitter. \r\n\r\nStack the potato slices in the dish, quite tightly. They will shrink a little as they cook. Drizzle with the olive oil and season well with sea salt and black pepper. Bake for 45 – 55 minutes, until the potatoes are golden and crispy around the edges. Serve immediately.', 2, '2024-12-27 09:28:15', '2024-12-27 11:24:19'),
(9, 'Pumpkin, pecan and pepita muffins', 'uploads/pumpkin-muffins2.webp', '1 3/4 cups self-raising flour\r\n1 teaspoon ground cinnamon\r\n1/4 teaspoon ground nutmeg\r\n1/4 teaspoon salt\r\n1 cup light brown sugar\r\n2/3 cup chopped pecans\r\n1/2 cup pepitas\r\n1/2 cup vegetable oil\r\n1/3 cup milk\r\n1 cup cooked, mashed pumpkin\r\n1 tablespoon maple syrup\r\n1 teaspoon vanilla\r\n2 eggs', 'Preheat oven to 180 C. Line a 12-hole muffin tin with paper cases. To make the mashed pumpkin roast at 180 C about 500 g Kent chopped pumpkin (with skin on), drizzled with a little canola oil for about 30 minutes or until soft.\r\nWhen cool enough to handle, scoop the flesh out of the skin and mash with a fork. To make the muffins sift the flour, cinnamon, nutmeg, salt and sugar into a medium sized mixing bowl. Add the pecans and mix well. In another bowl whisk together the vegetable oil, milk, mashed pumpkin, maple syrup, vanilla and eggs.\r\n\r\nTip the dry ingredients into the wet ingredients and combine quickly. Do not over beat of the muffins will be tough. Spoon the mixture evenly into the muffin tin and sprinkle the pepitas on top. Bake for 25 – 30 minutes until the muffins spring back when gently touched with your fingertips. Eat warm or at room temperature on their own, or with butter and a drizzle of honey.\r\n', 2, '2024-12-27 09:30:02', '2024-12-27 11:24:19'),
(10, 'Chilli prawns with pasta', 'uploads/chilli-prawns.webp', '1 tablespoon olive oil\r\n4 cloves garlic, finely chopped\r\n1 long red chilli, finely chopped\r\n80 ml white wine\r\n60 g butter\r\n1 kg tiger prawn, peeled and de-veined\r\n400g dried spaghetti (get the best quality you can afford – it makes a difference to the result)\r\nzest of 1 large lemon, finely chopped\r\n2 tablespoons chopped flat leaf parsley\r\nsea salt and black pepper', 'Bring a large pot of water to the boil. Heat the olive oil in a large frying pan over medium heat. Saute the garlic and chilli for a couple of minutes.  As soon as the water is boiling, add the pasta to the pot. Add the wine to the pan with the chilli and garlic and cook for a minute or two. Add the prawns and cook until they change colour and are just cooked through. By this time the pasta should be just about ready. Add the butter to the prawns and stir to coat them. Drain the pasta in a colander and then add to the prawns. Toss together with the lemon zest and parsley, check the seasoning and add salt to taste. Serve immediately.', 2, '2024-12-27 09:31:27', '2024-12-27 11:24:19'),
(11, 'Ham and Cheese Danish', 'uploads/ham-and-cheese-danish.jpg', 'puff pastry sheets\r\n1 bunch fresh basil\r\n1/2 cup pine nuts\r\n1/2 cup parmesan cheese, grated\r\n1/2 cup olive oil\r\njuice of 1 lemon\r\nsliced ham\r\nsliced cheese\r\n1 egg, whisked', 'In a food processor, blend basil, pine nuts, parmesan, olive oil, and lemon juice until it forms a chunky pesto.\r\nCut each puff pastry sheet in half, then fold each piece in half again for a double layer. Lay each piece flat like a diamond.\r\nSpoon pesto down the centre of the pastry, then layer on some cheese and ham.\r\nFold the two outer corners into the middle so they just touch. Press gently to seal.\r\nBrush the pastry with whisked egg for that golden shine ✨.\r\nBake in a preheated oven at 200°C for about 20 minutes or until golden brown.\r\nLet them cool slightly before devouring (if you can wait that long)!\r\n', 2, '2024-12-27 09:33:15', '2024-12-27 11:24:19'),
(12, 'Tortilla Omelette', 'uploads/Tortilla-Omelette.jpg', '2 large eggs\r\n1 tortilla\r\n1/4 cup shredded cheese (cheddar, mozzarella, or your favourite)\r\n1/4 cup diced vegetables (bell peppers, onions, tomatoes, or your choice)\r\nOptional: crispy bacon bits, ham, or any preferred protein\r\nSalt and pepper to taste\r\nCooking spray or a brush of oil\r\n', 'pour your eggs into the pan.\r\nAdd your fillings and cover with your tortilla.\r\nLet it cook for a few minutes and turn out on your plate!', 2, '2024-12-27 09:34:46', '2024-12-27 11:24:19'),
(13, 'Baked Feta Pasta', 'uploads/pasta.webp', '2 pints (20 ounces) cherry tomatoes\r\n\r\n\r\n1/2 cup extra-virgin olive oil\r\n\r\n\r\nKosher salt and freshly ground black pepper\r\n\r\n\r\nOne 8-ounce block feta cheese, drained (see Cook’s Note)\r\n\r\n\r\n10 ounces mezze rigatoni\r\n\r\n\r\n1 clove garlic, finely grated\r\n\r\n\r\nPinch crushed red pepper flakes, optional\r\n\r\n\r\n1/4 cup fresh basil leaves, thinly sliced\r\n\r\n\r\nFlaky sea salt, for serving', 'Preheat the oven to 400 degrees F.\r\nToss the cherry tomatoes and olive oil with 1/4 teaspoon of salt and several grinds of black pepper in a medium bowl until combined. Transfer to a 2 1/2- to 3-quart baking dish, place the feta in the center of the tomatoes and season with a pinch of black pepper. Bake until the tomatoes have burst and the feta has softened, about 30 minutes. Raise the heat to 450 degrees F and continue to cook until the tomatoes and feta are golden brown, 10 to 15 minutes more. \r\nMeanwhile, bring a large pot of generously salted water to a boil over high heat. Add the pasta and cook until al dente, about 13 minutes. Reserve 1/2 cup of the cooking water, then thoroughly drain the pasta. \r\nAs soon as the tomatoes and feta come out of the oven, stir in the garlic and red pepper flakes (if using). Use the back of a spoon to smash the tomatoes and feta into a smooth and creamy sauce (it’s okay if some of the oil isn’t fully integrated). Add the pasta and half the basil and toss until evenly coated. If the sauce is too thick, stir in some pasta water a couple tablespoons at a time. Taste and adjust the seasoning with salt and pepper. Serve topped with the remaining basil and a pinch of sea salt.', 2, '2024-12-27 09:39:05', '2024-12-27 11:24:19'),
(14, 'Saucy Gochujang Noodles with Chicken', 'uploads/Gochujang-Noodles.jpg', 'Gochujang Sauce:\r\n\r\n3 tablespoons soy sauce\r\n2–3 tablespoons gochujang sauce (like this one (affiliate link))\r\n2 tablespoons tomato paste\r\n2 tablespoons peanut butter\r\n2 tablespoons water\r\n1–2 tablespoons brown sugar\r\n1 tablespoon sesame oil\r\n1 clove minced garlic\r\n1–2 cups broth or water for thinning the sauce\r\nRamen:\r\n\r\n1 pound ground chicken (could also use pork)\r\n1/2 teaspoon salt\r\nfreshly ground black pepper\r\n2 packets ramen or stir fry noodles (just the noodles)\r\n1–2 cups fresh spinach\r\n1/4 cup chives, scallions, cilantro, basil, or whatever herbs you like for topping\r\nsalt to taste\r\n1 tablespoon chili oil for finishing\r\n1 tablespoon sesame seeds for finishing', 'Whisk the sauce ingredients (except the extra broth) in a small bowl or shake together in a jar. It should form a thick sauce.\r\nCook the chicken in a large skillet over medium high heat. Season generously with salt and pepper. \r\nBoil the noodles for just a few minutes to soften. Drain and set aside.\r\nWhen the chicken is done, add spinach, cooked noodles, and sauce to the pan, keeping it over medium high heat. Toss to combine; heat until the spinach is wilted. Add extra water or broth to thin the sauce, a little at a time, to get the sauciness that you like (I usually add about 1 1/2 cups total). \r\nServe topped with fresh herbs, scallions, chili oil, sesame seeds, and whatever else you like. ', 2, '2024-12-27 11:04:30', '2024-12-27 11:24:19'),
(15, 'Mac and Cheese', 'uploads/Mac-and-Cheese.jpg', '1 pound uncooked elbow pasta\r\n4 cups water\r\n1 teaspoon salt\r\n3 tablespoons butter, cut into small pieces\r\n2 1/2 cups shredded cheese\r\nup to 1/2 cup whole milk', 'Noodles: Put the pasta, water, and salt into the Instant Pot. Cook for 4 minutes using the manual function. Quick release the steam so your noodles don’t get overcooked. \r\nCheese: Gently stir in the butter until melted. Add the cheese and milk (use 2-3 tablespoons of milk at a time, as needed, up to 1/2 cup). Add more seasoning or liquid if necessary. For best results, let it sit for 5-10 minutes to let it thicken up a bit. MWAH! Enjoy. It’s so, so good.', 2, '2024-12-27 11:06:10', '2024-12-27 11:24:19'),
(16, 'Harissa Meatballs with Whipped Feta', 'uploads/Meatballs.jpg', 'Meatballs and Such:\r\n\r\none 22-ounce bag of store-bought frozen meatballs (or homemade, if you’ve got them / got the time)\r\n2 bell peppers (yellow and red), sliced\r\n1–2 zucchini, sliced into half moons\r\n2 tablespoons harissa paste\r\nolive oil, garlic powder, lemon juice, salt\r\nWhipped Feta:\r\n\r\none 6-ounce container feta cheese\r\n1–2 ounces cream cheese or sour cream or I’ve used plain yogurt in a pinch\r\n1 clove garlic\r\nExtras:\r\n\r\n1 cup hummus\r\n6 pitas\r\n1/4 cup kalamata olives\r\n1 lemon, cut into wedges', 'Sheet Pan, Part One: Preheat the oven to 425 degrees. Place the peppers on one side of a large sheet pan. Drizzle with oil and sprinkle with salt. Mix the harissa with a little bit of olive oil, lemon juice, and garlic powder until you have a nice spreadable red paste. Coat your meatballs with the sauce (you can do this by tossing the meatballs in a bowl with the sauce if they’re pre-cooked, or just brushing the meatballs directly on the sheet pan if your meatballs are raw). Add meatballs to the center of the sheet pan. Bake for 15-20 minutes.\r\n\r\nSheet Pan, Part Two: Add the zucchini to the pan with some olive oil and salt. Roast for another 10 minutes. For extra browning on everything, broil for about 5 minutes.\r\n\r\nWhip That Feta: In a food processor, chopper, or blender, whip up the feta, cream cheese, and garlic until a thick and creamy sauce forms. \r\n\r\nServe: Serve meatballs and veggies with a dollop of hummus, your whipped feta, pita wedges, and anything else you like (olives, lemon, etc.). And now DEVOUR. And repeat. And repeat. And repeat.', 2, '2024-12-27 11:08:24', '2024-12-27 11:24:19'),
(17, 'Springy Blueberry Lemon Bread', 'uploads/Lemon-Bread.jpg', '1/2 cup Land O Lakes® Butter, room temperature\r\n1 cup white sugar\r\njuice and zest of one lemon\r\n2 eggs\r\n1 1/2 cups flour\r\n1 teaspoon baking powder\r\n1 teaspoon salt\r\n1/2 cup milk\r\n1 cup blueberries – I used frozen without thawing them\r\nLand O Lakes® Butter with Olive Oil and Sea Salt for topping!', 'Prep: Preheat the oven to 350 degrees. Line a loaf pan with parchment paper.\r\nMix Part One: Cream the butter and sugar until fluffy. Mix in the lemon juice, lemon zest, and eggs.\r\nMix Part Two: Stir in the flour, baking powder, salt, and milk until the batter is mixed. Gently fold in the blueberries.\r\nBake: Pour batter into prepared pan. Bake for about one hour – the top should be golden brown and spring back when you touch it.\r\nServe: Let cool. Slice, slather on the butter with olive oil, and serve!', 2, '2024-12-27 11:10:16', '2024-12-27 11:24:19'),
(18, 'Golden Grahams Bars', 'uploads/Golden-Grahams.jpg', '6 tablespoons butter\r\n1 1/2 cups chocolate chips\r\n1 bag of mini marshmallows\r\n1 teaspoon vanilla\r\n1 12-ounce box of Golden Grahams cereal (see notes)', 'rep: Set one cup of the mini marshmallows aside.\r\nChocolate Mixture: Melt the butter, chocolate chips, mini marshmallows, and vanilla in a large pot over medium heat until mostly smooth.\r\nAdd Golden Grahams: Mix in the Golden Grahams cereal and remaining marshmallows. Stir to combine.\r\nPress Into Pan: Press into a 9×13 pan. Let them cool / solidify for an hour or two. Cut into 12 big bars and devour like a hungry Golden Grahams Bar wolf.', 2, '2024-12-27 11:11:33', '2024-12-27 11:24:19'),
(19, 'Almond Butter Chocolate Chip Zucchini Bars', 'uploads/Zucchini-Bars.jpg', '2 cups rolled oats\r\n1/4 cup + 2 tablespoons olive oil\r\n1/4 cup almond butter\r\n1/4 cup maple syrup\r\n8 medjool dates, pitted\r\n1–2 zucchini, grated and squeezed once (about 2 cups total, divided)\r\n2 eggs\r\n1 teaspoon baking soda\r\npinch of kosher salt\r\nchocolate chips (optional, for topping)', 'Preheat the oven to 350 degrees. Set aside about half of the zucchini and chocolate chips to stir in later. Blend everything else together until a smooth-ish batter comes together.\r\n\r\nStir in chocolate chips and zucchini. Pour batter into a square baking dish (9×9 or similar). Bake for 30-40 minutes, until the top is golden brown and gently springs back when you press into it.\r\n\r\nFor clean cuts, let it cool completely. (Or for hungry bellies, just get into it right warm out of the oven.) I like to store this in the refrigerator but you can serve warm or cold ALL DAY LONG! Snack, breakfast, dessert, all of it. ♡\r\n\r\nNotes\r\nFor a date-free version, use 1/2 cup almond butter and 1/2 cup maple syrup (and omit the dates). Still delicious!', 2, '2024-12-27 11:13:10', '2024-12-27 11:24:19'),
(20, 'Buttermilk Chicken', 'uploads/Buttermilk-Chicken.jpg', 'Crispy Chicken Bites\r\n300 g Chicken breast, cubed or sliced\r\n\r\n2 tsps curry powder\r\n\r\n1 tsp oyster sauce\r\n\r\n1/4 tsp salt\r\n\r\n1/4 tsp pepper\r\n\r\n1/2 egg (beat an egg, and scoop out half of the beaten eggs)\r\n\r\nto coat and fry\r\n1/4 cup cornstarch\r\n\r\n1/4 cup rice flour\r\n\r\nenough oil, for frying\r\n\r\nbuttermilk sauce\r\n1 tbsp butter\r\n\r\n2 cloves garlic, minced\r\n\r\n2 sprigs curry leaves\r\n\r\n1-2 bird’s eye chilli (cili padi)\r\n\r\n1 cup evaporated milk\r\n\r\n2 tbsps condensed milk (or 1 tbsp sugar)\r\n\r\n1/4 cup water (optional)\r\n\r\n1 cheese slice (optional)\r\n\r\ncilantro and spring onions, for garnish', 'To the chicken, season with salt and pepper, curry powder and oyster sauce. Toss to combine. Option to let this marinade overnight.\r\nAdd the egg to the chicken and combine to coat. Meanwhile, combine cornstarch and rice flour. Add the chicken pieces to the flour mixture and coat. Shake off any excess flour.\r\nTo a pan, add enough cooking oil to pan fry or deep fry. Heat over medium heat until hot.\r\nLay chicken pieces in the oil and allow to cook and crisp up on one side for about 3-4 minutes, before flipping over to the other side to fully cook and crisp. If deep-frying, deep fry for about 8 minutes. Once chicken is crispy and cooks through, remove from the oil. Place chicken bites in a paper towel to drain any excess oil.\r\nHeat pan over medium heat, and add oil. Once hot, add butter and allow to melt.\r\nOnce butter melts, add garlic, bird’s eye chillies and the curry leaves. Stir fry to release the fragrance.\r\nOnce fragrant, add the evaporated milk, condensed milk, salt and pepper, to taste. Stir to combine. Let the sauce come to a boil.\r\nOnce boiling, add water and cheese slice, if using. Stir to combine with the sauce until the cheese fully melts.\r\nAdd back the chicken and toss to combine. Once chicken is coated, turn off the heat. Plate and serve immediately! The sauce will further thicken as it cools.', 2, '2024-12-27 11:15:25', '2024-12-27 11:24:19'),
(21, 'Beef Rendang', 'uploads/rendang.webp', '⅜ pound shallots\r\n\r\n3 cloves garlic\r\n\r\n15 dried red chile peppers\r\n\r\n5 slices fresh ginger root\r\n\r\n5 lemon grass, chopped\r\n\r\n2 teaspoons coriander seeds\r\n\r\n2 teaspoons fennel seeds\r\n\r\n2 teaspoons cumin seeds\r\n\r\n1 pinch grated nutmeg\r\n\r\n1 tablespoon vegetable oil\r\n\r\n1 ¼ pounds beef stew meat, cut into 1 inch cubes\r\n\r\n1 ½ tablespoons white sugar\r\n\r\n2 cups shredded coconut\r\n\r\n5 whole cloves\r\n\r\n1 cinnamon stick\r\n\r\n1 ⅔ cups coconut milk\r\n\r\n⅞ cup water\r\n\r\nsalt to taste', 'Heat the coconut in a dry wok, stirring continuously until golden brown. Set aside to cool.\r\n\r\nUsing a blender or a food processor, blend the shallots, garlic, chilies, ginger, and lemon grass to a thick paste.\r\n\r\nGrind the coriander, fennel, cumin and nutmeg.\r\n\r\nUsing the wok, fry the shallot paste in a little oil for a few minutes. Add the ground coriander, fennel, cumin and nutmeg; cook for 3 to 4 minutes, stirring continuously. Add beef; cook over a medium heat for a further 3 to 4 minutes, or until meat is browned.\r\n\r\nStir in sugar, coconut, cloves, cinnamon stick, coconut milk , and water. Bring to a boil, lower heat, and simmer until most of the liquid has gone and the meat is tender (about 1 hour). Season with salt to taste.', 2, '2024-12-27 11:16:28', '2024-12-27 15:30:58'),
(22, 'Nasi Lemak', 'uploads/nasi lemak.jpg', '1) 3 cups of rice (washed)\r\n2) 300ml of Kara coconut milk\r\n3) One tablespoon of salt\r\n4) Pandan leaves (about 8 pieces and washed and tie a knot)\r\n5) Lemon Grass (4 stalks)\r\n6) Ginger (8 slices)', 'Wash the rice and pour in the coconut milk, salt, lemon grass, pandan leaves and ginger. Add the water to level 3 of the rice cooker and cook it.\r\nOnce it is done, mixed the rice in the cooker so that the coconut milk is evenly mixed around.\r\nFor the side dishes, it is optional for individual to cook whatever they like.\r\nSee the video link for the VFC teaching.', 2, '2024-12-27 11:17:34', '2024-12-27 15:31:19'),
(24, 'Spicy Tomato Chicken ', 'uploads/ayam-merah.webp', '1 (3 pound) whole chicken, cut into 8 pieces\r\n\r\n1 teaspoon ground turmeric\r\n\r\nsalt to taste\r\n\r\n¼ cup dried red chile peppers\r\n\r\n3 fresh red chile pepper, finely chopped\r\n\r\n4 cloves garlic, minced\r\n\r\n1 red onion, chopped\r\n\r\n1 (3/4 inch thick) slice fresh ginger root\r\n\r\n2 tablespoons sunflower seed oil\r\n\r\n1 cinnamon stick\r\n\r\n2 whole star anise pods\r\n\r\n5 whole cloves\r\n\r\n5 cardamom seeds\r\n\r\n2 tomatoes, sliced\r\n\r\n2 tablespoons ketchup\r\n\r\n1 teaspoon white sugar, or to taste\r\n\r\n½ cup water', 'Rub the chicken with turmeric powder and salt. Set aside. Soak the dried red chile peppers in hot water until softened. Blend the softened dried chile, fresh red chile pepper, garlic, onion, and ginger in a blender to a paste.\r\n\r\nHeat the oil in a large skillet over medium-high heat. Brown the chicken in the hot oil until golden on all sides. Remove the chicken from the skillet and set aside. Remove excess oil from the skillet, leaving about 1 tablespoon. Cook and stir the chile paste with the cinnamon, star anise, cloves and cardamom seeds until fragrant. Return the chicken to the skillet. Stir in the water, adding more if needed. Toss in the tomatoes and stir in the ketchup and sugar. Bring to a boil then reduce heat to medium-low and simmer until no the chicken longer pink at the bone and the juices run clear, about 15 minutes. Serve hot.', 2, '2024-12-27 15:26:19', '2024-12-27 15:26:19'),
(25, 'Beef Steaks', 'uploads/beef-steak.webp', '4 teaspoons salt, or to taste\r\n\r\n2 teaspoons paprika\r\n\r\n1 ½ teaspoons ground black pepper\r\n\r\n¾ teaspoon onion powder\r\n\r\n¾ teaspoon garlic powder, or to taste\r\n\r\n¾ teaspoon cayenne pepper, or to taste\r\n\r\n¾ teaspoon ground coriander, or to taste\r\n\r\n¾ teaspoon ground turmeric, or to taste\r\n\r\n4 (16 ounce) t-bone steaks, at room temperature', 'STEP 1\r\nGather all ingredients.\r\n\r\nSTEP 2 \r\nPreheat an outdoor grill for high heat and lightly oil the grate.\r\n\r\nSTEP 3\r\nStir together salt, paprika, black pepper, onion powder, garlic powder, cayenne pepper, coriander, and turmeric in a small bowl.\r\n\r\nSTEP 4\r\nRub seasoning over steaks on all sides.\r\n\r\nSTEP 5 \r\nCook steaks on the preheated grill to the desired degree of doneness, 3 to 3 1/2 minutes per side for medium-rare. An instant-read thermometer inserted into the center of each steak should read 130 degrees F (54 degrees C).', 2, '2024-12-27 15:29:06', '2024-12-27 15:29:06');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `role` enum('user','admin') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `email`, `created_at`, `role`) VALUES
(1, 'farah', '$2y$10$Vz/4Lpr7rmZMI18Q5Arwv.387BDYAnYb4eh0wuaPszNV6/ulkJdGu', 'sabrinafarah01@gmail.com', '2024-12-26 11:18:46', 'user'),
(2, 'admin', '$2y$10$UDe4ydx7fElLrKLhZZ0YiOCvccadGrUcKEit.pNGDz8RDJ453NMey', 'admin@example.com', '2024-12-26 12:01:01', 'admin'),
(6, 'Ara', '$2y$10$AAUgwiJDLL8Z/Z3H68lG6.sLH9RoBwBCJUWCmahUTNJeKGcyhj1CO', 'sabrinafarah@gmail.com', '2024-12-26 12:22:34', 'user'),
(7, 'frhsbrn_', '$2y$10$C2/686pGyX77as6HEN6f7.o2cyoVu8Yffw61FBI4knDQ7eqyWVVv.', 'ellieszgpbell@hotmail.com', '2024-12-26 14:00:13', 'user');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `recipes`
--
ALTER TABLE `recipes`
  ADD CONSTRAINT `recipes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
